services:
  cassandra-dc1-seed:
    image: cassandra:5.0.4
    ports:
      - "9042:9042"
      - "7199:7199"
      - "9100:9100"
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra_cl
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1 
      - CASSANDRA_SEEDS=cassandra-dc1-seed
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - HEAP_NEWSIZE=256M
      - MAX_HEAP_SIZE=475M
      - JVM_OPTS=-Xms256m -Xmx512m -javaagent:/jmx/jmx_prometheus_javaagent-1.3.0.jar=9100:/jmx/cassandra.yml
    volumes:
      - cassandra_dc1_seed_data:/var/lib/cassandra
      - ./jmx-exporter:/jmx

  cassandra-dc1-node2:
    image: cassandra:5.0.4
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra_cl
      - JVM_OPTS=-Xms256m -Xmx512m -javaagent:/jmx/jmx_prometheus_javaagent-1.3.0.jar=9100:/jmx/cassandra.yml
      - CASSANDRA_SEEDS=cassandra-dc1-seed
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1 
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - HEAP_NEWSIZE=256M
      - MAX_HEAP_SIZE=475M
    depends_on:
      - cassandra-dc1-seed
    volumes:
      - cassandra_dc1_node2_data:/var/lib/cassandra
      - ./jmx-exporter:/jmx

  cassandra-dc1-node3:
    image: cassandra:5.0.4
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra_cl
      - CASSANDRA_SEEDS=cassandra-dc1-seed
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1 
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - HEAP_NEWSIZE=256M
      - MAX_HEAP_SIZE=475M
      - JVM_OPTS=-Xms256m -Xmx512m -javaagent:/jmx/jmx_prometheus_javaagent-1.3.0.jar=9100:/jmx/cassandra.yml
    depends_on:
      - cassandra-dc1-seed
    volumes:
      - cassandra_dc1_node3_data:/var/lib/cassandra
      - ./jmx-exporter:/jmx

  cassandra-dc2-seed:
    image: cassandra:5.0.4
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra_cl
      - CASSANDRA_SEEDS=cassandra-dc1-seed,cassandra-dc2-seed
      - CASSANDRA_DC=dc2
      - CASSANDRA_RACK=rack2
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - HEAP_NEWSIZE=256M
      - MAX_HEAP_SIZE=475M
      - JVM_OPTS=-Xms256m -Xmx512m -javaagent:/jmx/jmx_prometheus_javaagent-1.3.0.jar=9100:/jmx/cassandra.yml
    depends_on:
      - cassandra-dc1-seed
    volumes:
      - cassandra_dc2_seed_data:/var/lib/cassandra
      - ./jmx-exporter:/jmx

  cassandra-dc2-node2:
    image: cassandra:5.0.4
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra_cl
      - CASSANDRA_SEEDS=cassandra-dc1-seed,cassandra-dc2-seed
      - CASSANDRA_DC=dc2
      - CASSANDRA_RACK=rack2
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - HEAP_NEWSIZE=256M
      - MAX_HEAP_SIZE=475M
      - JVM_OPTS=-Xms256m -Xmx512m -javaagent:/jmx/jmx_prometheus_javaagent-1.3.0.jar=9100:/jmx/cassandra.yml
    depends_on:
      - cassandra-dc2-seed
    volumes:
      - cassandra_dc2_node2_data:/var/lib/cassandra
      - ./jmx-exporter:/jmx

  cassandra-dc2-node3:
    image: cassandra:5.0.4
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra_cl
      - CASSANDRA_SEEDS=cassandra-dc1-seed,cassandra-dc2-seed
      - CASSANDRA_DC=dc2
      - CASSANDRA_RACK=rack2
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - HEAP_NEWSIZE=256M
      - MAX_HEAP_SIZE=475M
      - JVM_OPTS=-Xms256m -Xmx512m -javaagent:/jmx/jmx_prometheus_javaagent-1.3.0.jar=9100:/jmx/cassandra.yml
    depends_on:
      - cassandra-dc2-seed
    volumes:
      - cassandra_dc2_node3_data:/var/lib/cassandra
      - ./jmx-exporter:/jmx

  prometheus:
    image: quay.io/prometheus/prometheus:v3.4.1
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - cassandra-dc1-seed
      - cassandra-dc2-seed
      - cassandra-dc1-node2
      - cassandra-dc1-node3
      - cassandra-dc2-node2
      - cassandra-dc2-node3
  
  grafana:
    image: grafana/grafana-oss:12.0.1
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on: 
      - prometheus

volumes:
  cassandra_dc1_seed_data:
  cassandra_dc1_node2_data:
  cassandra_dc1_node3_data:
  cassandra_dc2_seed_data:
  cassandra_dc2_node2_data:
  cassandra_dc2_node3_data:
  grafana_data:
