services:
  cassandra-dc1-seed:
    image: cassandra:5.0.4
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra_cl
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1 
      - CASSANDRA_SEEDS=cassandra-dc1-seed
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - JVM_OPTS=-Xms256m -Xmx512m
      - HEAP_NEWSIZE=256M
      - MAX_HEAP_SIZE=475M
    volumes:
      - cassandra_dc1_seed_data:/var/lib/cassandra

  cassandra-dc1-node2:
    image: cassandra:5.0.4
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra_cl
      - JVM_OPTS=-Xms256m -Xmx512m
      - CASSANDRA_SEEDS=cassandra-dc1-seed
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1 
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - HEAP_NEWSIZE=256M
      - MAX_HEAP_SIZE=475M
    depends_on:
      - cassandra-dc1-seed
    volumes:
      - cassandra_dc1_node2_data:/var/lib/cassandra

  cassandra-dc1-node3:
    image: cassandra:5.0.4
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra_cl
      - JVM_OPTS=-Xms256m -Xmx512m
      - CASSANDRA_SEEDS=cassandra-dc1-seed
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1 
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - HEAP_NEWSIZE=256M
      - MAX_HEAP_SIZE=475M
    depends_on:
      - cassandra-dc1-seed
    volumes:
      - cassandra_dc1_node3_data:/var/lib/cassandra

  cassandra-dc2-seed:
    image: cassandra:5.0.4
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra_cl
      - CASSANDRA_SEEDS=cassandra-dc1-seed,cassandra-dc2-seed
      - CASSANDRA_DC=dc2
      - CASSANDRA_RACK=rack2
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - JVM_OPTS=-Xms256m -Xmx512m
      - HEAP_NEWSIZE=256M
      - MAX_HEAP_SIZE=475M
    depends_on:
      - cassandra-dc1-seed
    volumes:
      - cassandra_dc2_seed_data:/var/lib/cassandra

  cassandra-dc2-node2:
    image: cassandra:5.0.4
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra_cl
      - CASSANDRA_SEEDS=cassandra-dc1-seed,cassandra-dc2-seed
      - CASSANDRA_DC=dc2
      - CASSANDRA_RACK=rack2
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - JVM_OPTS=-Xms256m -Xmx512m
      - HEAP_NEWSIZE=256M
      - MAX_HEAP_SIZE=475M
    depends_on:
      - cassandra-dc2-seed
    volumes:
      - cassandra_dc2_node2_data:/var/lib/cassandra

  cassandra-dc2-node3:
    image: cassandra:5.0.4
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra_cl
      - CASSANDRA_SEEDS=cassandra-dc1-seed,cassandra-dc2-seed
      - CASSANDRA_DC=dc2
      - CASSANDRA_RACK=rack2
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - JVM_OPTS=-Xms256m -Xmx512m
      - HEAP_NEWSIZE=256M
      - MAX_HEAP_SIZE=475M
    depends_on:
      - cassandra-dc2-seed
    volumes:
      - cassandra_dc2_node3_data:/var/lib/cassandra

volumes:
  cassandra_dc1_seed_data:
  cassandra_dc1_node2_data:
  cassandra_dc1_node3_data:
  cassandra_dc2_seed_data:
  cassandra_dc2_node2_data:
  cassandra_dc2_node3_data:
